# Environment configuration
env: CarpoleSwingUp          # env name
train_params:                     # model contexts for training
- masscart: [0.25, 0.5, 1.5, 2.5]
  masspole: [0.5, 1.0, 1.5, 2.0]
  polelength: [0.3, 0.5, 0.7]
  gravity: [6.8, 9.8, 12.8]
  force_mag: [5.0, 10.0, 15.0]
test_range:                       # model contexts for testing
- masscart: [1.5, 2.5]
  masspole: [1.5, 2.0]
  polelength: [0.5, 0.7]
  gravity: [9.8, 12.8]
  force_mag: [10.0, 15.0]
n_itr: 10                         # number of time to re-run tests
normalize_flag: False             # normalize state
trail_length: 200                 # Inital traj count
num_trials: 10                    # Number of episodes

# Agent configuration
agent:
  horizon: 15                   # how long of the horizon to predict
  popsize: 500                  # how many random samples for mpc
  alpha: 0.01
  replan_freq: 1
  num_iters: 20
  elite_ratio: 0.1
  max_particles: 20

# Model arch parameters
context:
  hidden_dim: 256
  hidden_layers: 1
  out_dim: 128
  history_size: 16

backbone:
  hidden_dim: 256
  hidden_layers: 1
  out_dim: 128

head:
  load_model: False
  model_path: "./saves/head.ckpt"
  hidden_dim: 256
  hidden_layers: 1
  ensemble_size: 5

# Dynamics model training config
dynamics:
  learning_rate: 0.003
  batch_size: 512
  validation_ratio: 0.05         # ratio of validation set

# "Trajectory-wise Multiple Choice Learning for Dynamics Generalization
# in Reinforcement Learning" parameters
TW:
  history_length: 10
  future_length: 10
  state_diff: 0
  non_adaptive_planning: 0
